=== muhkuh-sys/org.muhkuh.tests-skeleton/jonchki/testcase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="jonchki-artifact">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="info">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="license">
								<xs:complexType>
									<xs:attribute name="name" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="author">
								<xs:complexType>
									<xs:attribute name="name" use="required" />
									<xs:attribute name="url" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="description" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="group" use="required" />
						<xs:attribute name="module" use="required" />
						<xs:attribute name="artifact" use="required" />
						<xs:attribute name="version" use="required" />
						<xs:attribute name="vcs-id" use="required" />
						<xs:attribute name="extension" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="dependencies">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dependency" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="group" use="required" />
									<xs:attribute name="module" use="required" />
									<xs:attribute name="artifact" use="required" />
									<xs:attribute name="version" type="xs:decimal" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== muhkuh-sys/org.muhkuh.tests-skeleton/testcase_1234.567R8.xml
<?xml version="1.0" encoding="UTF-8"?>
<jonchki-artifact xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="jonchki/testcase.xsd"
                  version="1.0">
	<info group="com.hilscher.productiontests"
	      module="productiontests"
	      artifact="1234.567R8_demo_board"
	      version="0.0.1"
	      vcs-id="${prj_version_vcs_long}"
	      extension="tar.gz">
		<license name="PROPRIETARY"/>
		<author name="Change me" url="https://www.hilscher.com/" />
		<description>
			A board test for the demo board.
		</description>
	</info>
	<dependencies>
		<dependency group="org.muhkuh.tools"         module="muhkuh_tester_webui"   artifact="lua5.4-muhkuh_tester_webui" version="0.0"/>
		<dependency group="org.muhkuh.tests"         module="bootpins"              artifact="bootpins"                   version="1.3"/>
	</dependencies>
	<actions>
		<action name="finalizer" file="${define_finalizer}"/>
	</actions>
</jonchki-artifact>
